# Pod에서 env(환경변수) 사용 예문
# configMap이나 Secret 파일을 직접 마운트해서 가져오는 Volume 예문은 따로 정리하겠음
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: test
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    envFrom: # Secret(또는 ConfigMap)에 있는 모든 key-value를 환경변수로 가져옴, 단일로 가져올땐 env: 를 사용하면 된다 
             # 자세한건 kubectl explain pod.spec.containers.envFrom 하위 참조
    - secretRef: # envFrom은 [] 리스트 형식이므로 앞에 '-' 를 반드시 붙여주어야 한다
        name: db-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}