apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx:alpine
    name: nginx
    resources: {}
    volumeMounts:
    - name: vol
      mountPath: /var/www/html
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: local-pvc
status: {}