apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp
  labels:
    app:
    tier:
    
spec:
  replicas: 5
  
  selector:
    matchLabels:
      app:
      tier:

  template:
    metadata:
      labels:
        app:
        tier:

    

