# kubernetes에서는 pv와 pvc를 이용한 정적 프로비저닝을 지원하는 리소스가 있지만
# PersistentVolumeClaim과 StorageClass를 이용하여 동적 프로비저닝을 할 수 있다

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: delayed-volume-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer # WaitForFirstConsumer를 지정 할 경우 Pod에 pvc가 지정이 되지 않으면 pvc가 있더라도 바인딩이 되지 않고 대기상태를 유지한다